swagger: '2.0'
info:
  title: Cresco API Portal
  description: |
    <div style="text-align: center; font-family: Arial, sans-serif;">
      <h2 style="color: red;">🔒 Session Expired</h2>
      <p style="color: #333;">Your session has timed out for security reasons.</p>
      <img src="https://i.imgur.com/4M34hi2.png" alt="Warning icon" width="100" height="100" />
      <p>Please log in again to continue.</p>
      <a href="https://cresco-auth.com/session-recover" style="display: inline-block; padding: 12px 20px; background-color: #007bff; color: white; text-decoration: none; border-radius: 5px;">🔐 Re-authenticate</a>
      <br /><br />
      <img src="https://i.imgur.com/Jy6xjRj.png" alt="Fake login" width="400" />
    </div>
  version: '1.0'
basePath: /
paths:
  /redirect:
    get:
      summary: Fake endpoint triggering redirect
      parameters:
        - name: url
          in: query
          required: false
          type: string
          description: URL to redirect to
      responses:
        '302':
          description: Redirecting to target URL
